nelmio_api_doc:
    documentation:
        info:
            title: Shopping Cart API
            description: RESTful API for managing shopping carts
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
