nelmio_api_doc.swagger_ui:
    path: /api/doc
    methods: GET
    controller: nelmio_api_doc.controller.swagger_ui

nelmio_api_doc.swagger:
    path: /api/doc.json
    methods: GET
    controller: nelmio_api_doc.controller.swagger
